### ISSUE TITLE
回答完问题，出现网络错误

### ISSUE THREAD

**Issue by jooewood** [RapidAI/Knowledge-QA-LLM#13]
![image](https://github.com/RapidAI/Knowledge-QA-LLM/assets/93376510/4aa0913f-dfc5-4a85-9063-2747c1fd83a2)

**Comment by jooewood** [comment]
问题是回答了，，回答完回跳一个这个奇怪的嘞
![image](https://github.com/RapidAI/Knowledge-QA-LLM/assets/93376510/30f0c508-7c0c-49e7-955c-b7bc214f5fbc)

**Comment by SWHL** [comment]
问题还没有回答，支持检索出来了。
下面网络出错，还是因为llm调用有问题。
可以试试在线版 https://aistudio.baidu.com/projectdetail/6675380

**Comment by jooewood** [comment]
![image](https://github.com/RapidAI/Knowledge-QA-LLM/assets/93376510/c4fc6e2a-12d5-47b9-b99f-dcab5cced46c)

**Comment by jooewood** [comment]
我本地版已经好了，话说，你这个知识库怎么没有删除的功能嘞

**Comment by SWHL** [comment]
> 在线版的，上传文件后报错 ![image](https://user-images.githubusercontent.com/93376510/264930677-c4fc6e2a-12d5-47b9-b99f-dcab5cced46c.png)

这个估计是文本超长了，待我排查一下

**Comment by SWHL** [comment]
> 我本地版已经好了，话说，你这个知识库怎么没有删除的功能嘞

害，这不还没来得及搞嘛。
想着做前后端分离的，但是前端不会。现在基于streamlit，受限太多。
欢迎贡献哈

**Comment by jooewood** [comment]
我也不会前端唉，话说streamlit，怎么样啊，是不够灵活么

**Comment by SWHL** [comment]
是的，做demo还行，想要灵活部署使用，就够呛了。
