### ISSUE TITLE
when I load the the PDFs in test files，it occurs index error in finding similar embedding

### ISSUE THREAD

**Issue by leilichuan** [RapidAI/Knowledge-QA-LLM#9]
the shape of self.all_texts is (4,)
![image](https://github.com/RapidAI/Knowledge-QA-LLM/assets/24786137/9c7a6fe4-e257-48bf-b9a1-413bbd7a9c79)

**Comment by SWHL** [comment]
In the latest code, the problem has been fixed.
Please use the latest code.
